package mts.delhivery.com.mts.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LOCATION".
 */
public class Location {

    private Long id;
    private Double latitude;
    private Double longitude;
    private Float accuracy;
    private String device_id;
    private String application;
    private Long epoc;
    private String time;
    private Float battery;

    public Location() {
    }

    public Location(Long id) {
        this.id = id;
    }

    public Location(Long id, Double latitude, Double longitude, Float accuracy, String device_id, String application, Long epoc, String time, Float battery) {
        this.id = id;
        this.latitude = latitude;
        this.longitude = longitude;
        this.accuracy = accuracy;
        this.device_id = device_id;
        this.application = application;
        this.epoc = epoc;
        this.time = time;
        this.battery = battery;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Float getAccuracy() {
        return accuracy;
    }

    public void setAccuracy(Float accuracy) {
        this.accuracy = accuracy;
    }

    public String getDevice_id() {
        return device_id;
    }

    public void setDevice_id(String device_id) {
        this.device_id = device_id;
    }

    public String getApplication() {
        return application;
    }

    public void setApplication(String application) {
        this.application = application;
    }

    public Long getEpoc() {
        return epoc;
    }

    public void setEpoc(Long epoc) {
        this.epoc = epoc;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Float getBattery() {
        return battery;
    }

    public void setBattery(Float battery) {
        this.battery = battery;
    }

}
